#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TARGET_FILE="${ROOT_DIR}/gateway/dynamic/blue-green.yml"
BLUE="${BLUE_WEIGHT:-100}"
GREEN="${GREEN_WEIGHT:-0}"

if ! [[ "${BLUE}" =~ ^[0-9]+$ && "${GREEN}" =~ ^[0-9]+$ ]]; then
  echo "BLUE_WEIGHT and GREEN_WEIGHT must be integers."
  exit 1
fi

if (( BLUE + GREEN != 100 )); then
  echo "BLUE_WEIGHT + GREEN_WEIGHT must equal 100."
  exit 1
fi

cat > "${TARGET_FILE}" <<EOF
# Weighted routing for blue/green deployments.
# Generated by infrastructure/scripts/bluegreen-apply.sh
http:
  services:
    history-bluegreen:
      weighted:
        services:
          - name: history-blue
            weight: ${BLUE}
          - name: history-green
            weight: ${GREEN}
EOF

echo "Updated ${TARGET_FILE}: blue=${BLUE}, green=${GREEN}"
